### ISSUE TITLE
Update specs for `verify_relevant_tx_list`

### ISSUE THREAD

**Issue by rootulp** [Sovereign-Labs/sovereign#57]
The specs for `verify_relevant_tx_list` don't match the current implementation. In particular, the implementation returns a `Result` so it seems like the specs need to be updated.

https://github.com/Sovereign-Labs/sovereign/blob/ea2346a3322b6fc5f765d2d576bb1b81f68d94f8/sdk/specs/interfaces/da.md?plain=1#L137-L143

https://github.com/Sovereign-Labs/sovereign/blob/ea2346a3322b6fc5f765d2d576bb1b81f68d94f8/sdk/src/state_machine/da.rs#L42-L48

**Comment by preston-evans98** [comment]
@rootulp, thanks for opening this! It looks like the spec correctly shows a Result type here: https://github.com/Sovereign-Labs/sovereign/blob/ea2346a3322b6fc5f765d2d576bb1b81f68d94f8/sdk/specs/interfaces/da.md?plain=1#L161 - but because of the lack of Sum types in some languages the syntax we use in the spec is a bit awkward and easy to miss. 

If you have a suggestion for improving it, we'd love to hear!

**Comment by rootulp** [comment]
Proposal to remove the following lines under the **Usage** section:

> This method 
 returns the same list of transactions that would be returned by `get_relevant_txs`, in addition 
 to a witness proving the inclusion of these transactions in the DA layer block, and a witness 
 showing the completeness of the provided list. 

and add something like

> This method returns a Result type that contains an error if...

**Comment by preston-evans98** [comment]
Oh yeah, the description is completely wrong - looks like we copy-pasted and forgot to remove the irrelevant parts. Fixing now!
